import { useEffect, useState, FormEvent } from 'react'
import { Menu, X, Mail, Phone, Linkedin, ArrowUp, ArrowRight, Brain, Eye, Database, Cpu } from 'lucide-react'
import { profile, skills, services, projects, filters, education, Project } from './data'

const words=['Machine Learning','Computer Vision','Document AI','Data Science']
const links=['about','skills','services','projects','education','experience','contact']
const H=({id,t,s}:{id:string;t:string;s?:string})=>(<div className="mb-8"><h2 id={id+'-h'} className="text-2xl sm:text-3xl font-semibold bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent">{t}</h2>{s&&<p className="mt-2 text-slate-400 max-w-2xl">{s}</p>}<div className="mt-3 h-0.5 w-12 bg-gradient-to-r from-blue to-violet"/></div>)
const Chip=({c}:{c:string})=><span className="rounded-full border border-line bg-ink px-2.5 py-1 text-xs text-slate-300">{c}</span>
const Sec=({id,children,alt}:{id:string;children:React.ReactNode;alt?:boolean})=><section id={id} aria-labelledby={id+'-h'} className={alt?'bg-panel/40':''}><div className="reveal mx-auto max-w-6xl px-5 py-16 sm:py-20">{children}</div></section>

function Art({id}:{id:string}){const c='#3b82f6',v='#8b5cf6',g='#94a3b8'
const box=<rect x="8" y="8" width="184" height="84" rx="6" fill="#0b1224" stroke="#1e2a44"/>
const B:Record<string,React.ReactNode>={
fireshield:<><rect x="8" y="8" width="124" height="84" rx="6" fill="#0b1224" stroke="#1e2a44"/><path d="M62 82 Q50 56 66 34 Q72 50 82 44 Q94 62 82 82Z" fill="#f97316"/><rect className="pulse" x="44" y="28" width="56" height="56" rx="3" fill="none" stroke="#22c55e" strokeWidth="1.5"/><text x="46" y="25" fontSize="6" fill="#22c55e">fire</text><circle className="pulse" cx="120" cy="18" r="3" fill="#ef4444"/><path className="dash" d="M132 50h16" stroke={c}/><rect x="148" y="36" width="44" height="28" rx="4" fill={v} opacity=".5"/><text x="156" y="53" fontSize="7" fill="#fff">ESP32</text></>,
rag:<><g fill="#0b1224" stroke="#1e2a44"><rect x="8" y="14" width="26" height="34" rx="3"/><rect x="14" y="22" width="26" height="34" rx="3"/><rect x="20" y="30" width="26" height="34" rx="3"/></g><path className="dash" d="M52 47h22" stroke={c}/><ellipse cx="90" cy="34" rx="14" ry="5" fill={v} opacity=".6"/><path d="M76 34v26c0 3 6 5 14 5s14-2 14-5V34" fill="none" stroke={v}/><text x="76" y="78" fontSize="6" fill={g}>ChromaDB</text><path className="dash" d="M108 47h22" stroke={c}/><rect x="134" y="28" width="30" height="36" rx="4" fill="#0b1224" stroke={c}/><path d="M140 38h18M140 46h14M140 54h10" stroke="#475569"/><circle className="pulse" cx="182" cy="40" r="8" fill="none" stroke="#22c55e"/><path d="M178 40l3 3 5-6" stroke="#22c55e" fill="none"/><text x="168" y="62" fontSize="6" fill={g}>Doctor</text></>,
stockvision:<>{box}{[20,32,26,44,38,55].map((h,i)=><rect key={i} x={16+i*16} y={80-h} width="10" height={h} fill={c} opacity=".8"/>)}<polyline className="draw" pathLength="100" points="16,60 40,48 64,52 88,34 112,40 136,22" fill="none" stroke={v} strokeWidth="1.5"/><rect x="128" y="50" width="56" height="30" rx="3" fill="#111a30"/><text x="134" y="62" fontSize="6" fill={g}>Inventory</text><text x="134" y="74" fontSize="6" fill="#f59e0b">illustrative</text></>,
ats:<><rect x="12" y="8" width="52" height="84" rx="4" fill="#e2e8f0"/><path d="M20 20h36M20 28h28M20 36h34M20 48h30M20 56h36M20 64h24" stroke={g} strokeWidth="2"/><rect className="scan" x="12" y="8" width="52" height="3" fill={c}/><path className="dash" d="M70 50h22" stroke={c}/><text x="72" y="44" fontSize="7" fill={c}>OCR</text><rect x="98" y="14" width="90" height="72" rx="4" fill="#0b1224" stroke="#1e2a44"/><g fontSize="7" fontFamily="monospace" fill={g}><text x="106" y="30">name: …</text><text x="106" y="44">skills: […]</text><text x="106" y="58">experience: …</text><text x="106" y="74" fill={v}>match → job</text></g></>,
docs:<><rect x="12" y="8" width="52" height="84" rx="4" fill="#e2e8f0"/><g stroke={g} strokeWidth="2"><path d="M20 20h36M20 34h36M20 48h36M20 70h20"/></g><rect x="20" y="56" width="6" height="6" fill="none" stroke={g}/><rect className="scan" x="12" y="8" width="52" height="3" fill={c}/><path className="dash" d="M70 50h16" stroke={c}/><text x="68" y="44" fontSize="6" fill={c}>preprocess</text><path className="dash" d="M96 50h12" stroke={v}/><text x="92" y="62" fontSize="6" fill={v}>OCR</text><rect x="112" y="14" width="76" height="72" rx="4" fill="#0b1224" stroke="#1e2a44"/><g fontSize="7" fontFamily="monospace" fill={g}><text x="118" y="32">field_1: …</text><text x="118" y="48">field_2: …</text><text x="118" y="64">field_3: …</text></g></>,
housing:<>{<rect x="8" y="8" width="110" height="84" rx="6" fill="#0b1224" stroke="#1e2a44"/>}{[[20,78],[30,70],[40,72],[50,58],[58,60],[68,48],[78,50],[88,36],[98,38],[106,24]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="2.5" fill={c}/>)}<line className="draw" pathLength="100" x1="16" y1="82" x2="110" y2="20" stroke={v} strokeWidth="1.5"/><rect x="132" y="50" width="22" height="34" fill={v} opacity=".7"/><rect x="162" y="49" width="22" height="35" fill={c}/><text x="134" y="94" fontSize="6" fill={g}>RF</text><text x="160" y="94" fontSize="6" fill={g}>XGBoost</text></>,
superstore:<>{box}{[30,44,36,52,46,62,56].map((h,i)=><rect key={i} x={18+i*24} y={86-h*.5} width="14" height={h*.5} fill={v} opacity=".6"/>)}<polyline className="draw" pathLength="100" points="20,70 44,56 68,62 92,40 116,48 140,28 164,34" fill="none" stroke={c} strokeWidth="2"/><text x="14" y="20" fontSize="6" fill="#f59e0b">illustrative sales trend</text></>}
return(<svg viewBox="0 0 200 100" className="block w-full" role="img" aria-label="Illustrative graphic for this project">{B[id]}</svg>)}

function DataBg(){return(<div aria-hidden className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
<svg className="absolute inset-0 h-full w-full" preserveAspectRatio="none" viewBox="0 0 1000 600"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stopColor="#3b82f6" stopOpacity="0"/><stop offset=".5" stopColor="#3b82f6" stopOpacity=".55"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs>
<g stroke="#1e2a44" strokeOpacity=".45">{[100,200,300,400,500].map(y=><line key={y} x1="0" x2="1000" y1={y} y2={y}/>)}</g>
<polyline className="draw" pathLength="100" points="0,420 120,380 240,400 360,300 480,330 600,220 720,260 840,150 1000,180" fill="none" stroke="url(#lg)" strokeWidth="2"/>
<polyline className="draw" pathLength="100" points="0,500 140,470 280,490 420,420 560,440 700,360 860,380 1000,300" fill="none" stroke="url(#lg)" strokeWidth="1.5" opacity=".5"/></svg>
{Array.from({length:14}).map((_,i)=><span key={i} className="animate-float absolute h-1.5 w-1.5 rounded-full bg-blue/50" style={{left:(i*37%96)+'%',top:(i*53%90)+'%',animationDelay:i*.4+'s'}}/>)}
<div className="absolute inset-x-0 bottom-0 flex h-40 items-end gap-1.5 px-2 opacity-[.07]">{Array.from({length:40}).map((_,i)=><span key={i} className="grow-bar flex-1 rounded-t bg-blue" style={{height:(20+(i*37)%80)+'%',animationDelay:i*.08+'s'}}/>)}</div></div>)}

function Flow({steps}:{steps:string[]}){return(<ol className="flex flex-col md:flex-row md:items-stretch gap-2" aria-label="Workflow diagram">
{steps.map((s,i)=>(<li key={s} className="flex md:flex-1 flex-col md:flex-row items-center gap-2"><div className="w-full md:flex-1 h-full rounded-lg border border-blue/40 bg-gradient-to-b from-blue/10 to-violet/10 px-3 py-3 text-center text-sm text-white">{s}</div>{i<steps.length-1&&<ArrowRight aria-hidden className="h-4 w-4 shrink-0 text-violet rotate-90 md:rotate-0"/>}</li>))}</ol>)}

function Mock(){const b=[40,55,48,70,62,85,78];return(<div className="rounded-lg border border-line bg-ink p-4"><p className="text-xs text-amber-300 mb-2">Illustrative mockup — sample data, not real business results</p>
<div className="flex items-end gap-2 h-24" role="img" aria-label="Illustrative bar chart mockup">{b.map((v,i)=><div key={i} style={{height:v+'%'}} className="flex-1 rounded-t bg-gradient-to-t from-blue to-violet"/>)}</div></div>)}

function Modal({p,onClose}:{p:Project;onClose:()=>void}){
useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',k);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',k);document.body.style.overflow=''}},[onClose])
const R=({l,v}:{l:string;v:string})=><div><h4 className="text-xs uppercase tracking-wider text-blue">{l}</h4><p className="mt-1 text-slate-300">{v}</p></div>
return(<div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/70 p-0 sm:p-6" onClick={onClose}>
<div role="dialog" aria-modal="true" aria-label={p.title} onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl sm:rounded-2xl border border-line bg-panel p-5 sm:p-8">
<div className="flex justify-between gap-4"><div><h3 className="text-xl sm:text-2xl font-semibold text-white">{p.title}</h3><p className="text-slate-400">{p.sub}</p></div>
<button autoFocus onClick={onClose} aria-label="Close case study" className="h-11 w-11 shrink-0 grid place-items-center rounded-lg border border-line hover:bg-line"><X className="h-5 w-5"/></button></div>
<p className="mt-3 inline-block rounded-full bg-violet/20 px-3 py-1 text-xs text-violet-200">Status: {p.status}</p>
<div className="mt-5 overflow-hidden rounded-lg border border-line bg-ink"><Art id={p.id}/></div><div className="mt-6 space-y-5"><R l="Overview" v={p.overview}/><R l="Objective" v={p.objective}/><R l="My contribution" v={p.contribution}/><R l="Technical approach" v={p.approach}/>
<div><h4 className="mb-2 text-xs uppercase tracking-wider text-blue">Workflow</h4><Flow steps={p.flow}/></div>
<R l="Documented outcome" v={p.outcome}/>
<div className="flex flex-wrap gap-2">{p.stack.map(c=><Chip key={c} c={c}/>)}</div>
<p className="text-xs text-slate-500">Repository / demo links: none published yet.</p></div></div></div>)}

function Lightbox({src,onClose}:{src:string;onClose:()=>void}){
useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[onClose])
return(<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4" onClick={onClose}><div role="dialog" aria-modal="true" aria-label="Certificate" className="relative w-full max-w-4xl" onClick={e=>e.stopPropagation()}>
<button autoFocus onClick={onClose} aria-label="Close certificate" className="absolute -top-12 right-0 h-11 w-11 grid place-items-center rounded-lg bg-panel text-white"><X className="h-5 w-5"/></button>
<img src={`${import.meta.env.BASE_URL}${src}`} alt="Training certificate" className="w-full rounded-lg"/></div></div>)}

export default function App(){
const[open,setOpen]=useState(false);const[active,setActive]=useState('');const[f,setF]=useState('All');const[sel,setSel]=useState<Project|null>(null);const[top,setTop]=useState(false)
const[cert,setCert]=useState<string|null>(null);const[w,setW]=useState(0);const[prog,setProg]=useState(0);const[err,setErr]=useState<Record<string,string>>({})
useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-40% 0px -55% 0px'});links.forEach(l=>{const el=document.getElementById(l);el&&o.observe(el)});const s=()=>{setTop(scrollY>600);setProg(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100)};addEventListener('scroll',s);return()=>{o.disconnect();removeEventListener('scroll',s)}},[])
useEffect(()=>{const t=setInterval(()=>setW(x=>(x+1)%4),2200);const r=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('in')),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>r.observe(el));return()=>{clearInterval(t);r.disconnect()}},[])
const list=projects.filter(p=>f==='All'||p.cats.includes(f))
const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const v=(k:string)=>String(d.get(k)||'').trim();const x:Record<string,string>={}
if(v('name').length<2)x.name='Please enter your name.';if(!/^\S+@\S+\.\S+$/.test(v('email')))x.email='Please enter a valid email.';if(v('subject').length<2)x.subject='Please add a subject.';if(v('message').length<10)x.message='Message should be at least 10 characters.'
setErr(x);if(Object.keys(x).length)return
location.href=`mailto:${profile.email}?subject=${encodeURIComponent(v('subject'))}&body=${encodeURIComponent(v('message')+'\n\n— '+v('name')+' ('+v('email')+')')}`}
const btn='inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-5 py-2.5 text-sm font-medium transition'
const inp='w-full rounded-lg border border-line bg-ink px-3 py-2.5 text-white'
return(<>
<a href="#about" className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:bg-blue focus:p-2">Skip to content</a>
<div aria-hidden className="fixed left-0 top-0 z-50 h-0.5 bg-gradient-to-r from-blue to-violet" style={{width:prog+'%'}}/>
<DataBg/>
<header className="sticky top-0 z-40 border-b border-line bg-ink/90 backdrop-blur"><nav aria-label="Main" className="mx-auto flex max-w-6xl items-center justify-between px-5 h-16">
<a href="#top" className="flex items-center gap-2.5" aria-label="Omar Ahmed El-Banna, home"><span className="grid h-9 w-9 place-items-center rounded-lg bg-gradient-to-br from-blue to-violet text-sm font-bold text-white">OE</span><span className="leading-tight"><span className="block text-sm font-semibold text-white">Omar El-Banna</span><span className="block text-[11px] text-slate-400">AI · ML · Data Science</span></span></a>
<ul className="hidden lg:flex gap-6 text-sm">{links.map(l=><li key={l}><a href={'#'+l} aria-current={active===l?'true':undefined} className={'capitalize pb-1 border-b-2 '+(active===l?'text-white border-blue':'text-slate-400 border-transparent hover:text-white')}>{l}</a></li>)}</ul>
<button className="lg:hidden h-11 w-11 grid place-items-center" aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>
{open&&<ul className="lg:hidden border-t border-line bg-ink px-5 pb-3">{links.map(l=><li key={l}><a href={'#'+l} onClick={()=>setOpen(false)} className="block py-3 capitalize text-slate-200">{l}</a></li>)}</ul>}</header>
<main id="top">
<section className="hero-bg relative overflow-hidden"><div aria-hidden className="absolute -top-32 right-0 h-96 w-96 rounded-full bg-blue/20 blur-3xl animate-float"/><div aria-hidden className="absolute top-40 -left-20 h-72 w-72 rounded-full bg-violet/15 blur-3xl"/>
<div className="relative mx-auto grid max-w-6xl items-center gap-10 px-5 py-10 sm:py-20 lg:grid-cols-2">
<div><p className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300"><span className="pulse h-2 w-2 rounded-full bg-emerald-400"/>Open to freelance projects</p><p className="mt-4 text-2xl font-semibold text-white sm:text-3xl">{profile.name}</p><p className="mt-2 inline-block rounded-full border border-line bg-panel px-3 py-1 text-sm text-slate-300">{profile.role}</p><p aria-hidden className="mt-3 h-7 text-lg text-blue">▸ <span key={w} className="inline-block animate-fade">{words[w]}</span></p>
<h1 className="mt-4 text-3xl sm:text-5xl font-bold leading-[1.12] tracking-tight text-white">Turning Data and Real-World Problems into <span className="animate-grad bg-gradient-to-r from-blue via-violet to-blue bg-[length:200%_auto] bg-clip-text text-transparent">Practical AI Solutions</span></h1>
<p className="mt-5 text-slate-300">I build Python-based AI, machine learning, data analysis, and computer vision projects focused on practical problems and useful outcomes.</p>
<p className="mt-4 border-l-2 border-violet pl-4 text-sm text-slate-400">{profile.usp}</p>
<div className="mt-7 flex flex-col sm:flex-row gap-3"><a href="#projects" className={btn+' bg-blue text-white hover:bg-blue/80'}>Explore My Projects</a><a href="#contact" className={btn+' border border-line hover:bg-line text-white'}>Contact Me</a></div></div>
<div className="relative order-first mx-auto grid aspect-square w-64 place-items-center sm:w-[26rem] lg:order-last"><div aria-hidden className="animate-float absolute -left-6 bottom-6 z-10 hidden w-36 rounded-xl border border-line bg-panel/90 p-3 shadow-xl sm:block"><p className="text-[10px] text-slate-400">Data analysis</p><svg viewBox="0 0 100 30" className="mt-1 w-full"><polyline className="draw" pathLength="100" points="0,25 15,18 30,22 45,10 60,14 80,4 100,8" fill="none" stroke="#3b82f6" strokeWidth="2"/></svg></div>
<div aria-hidden className="animate-float absolute -right-4 top-6 z-10 hidden rounded-xl border border-line bg-panel/90 px-3 py-2 text-[11px] shadow-xl sm:block" style={{animationDelay:'1.5s'}}><span className="text-emerald-300">●</span> ML pipeline</div><div aria-hidden className="absolute inset-0 rounded-full border border-dashed border-line"/><div aria-hidden className="absolute inset-8 rounded-full border border-line/60"/>
<div aria-hidden className="orbit absolute inset-0">{[Brain,Eye,Database,Cpu].map((I,i)=><span key={i} className={'absolute '+['left-1/2 -top-5 -translate-x-1/2','-right-5 top-1/2 -translate-y-1/2','left-1/2 -bottom-5 -translate-x-1/2','-left-5 top-1/2 -translate-y-1/2'][i]}><span className="orbit-i grid h-11 w-11 place-items-center rounded-full border border-blue/40 bg-panel text-blue shadow-lg shadow-blue/20"><I className="h-5 w-5"/></span></span>)}</div>
<div className="relative w-40 sm:w-72"><div aria-hidden className="absolute -inset-1.5 rounded-full bg-gradient-to-br from-blue to-violet opacity-80 blur-sm"/><img src={`${import.meta.env.BASE_URL}omar.jpg`} alt="Portrait of Omar Ahmed El-Banna" width={400} height={400} className="relative aspect-square w-full rounded-full border border-line object-cover"/></div></div></div></section>

<Sec id="about"><H id="about" t="About Me"/><div className="grid items-start gap-8 md:grid-cols-[220px_1fr]"><div className="card w-full rounded-2xl border border-line bg-panel p-5 text-sm">{[['Education','Damanhour University · 4th year'],['Focus','AI · ML · Data Science'],['Training','NTI · Central Bank of Egypt · DEPI (ongoing)'],['Based in','Damanhour, Egypt']].map(([k,v])=><div key={k} className="border-b border-line py-2.5 first:pt-0 last:border-0 last:pb-0"><p className="text-xs uppercase tracking-wider text-blue">{k}</p><p className="mt-0.5 text-slate-200">{v}</p></div>)}</div><div className="max-w-3xl space-y-4 text-slate-300"><p>I'm a fourth-year Computers and Information student at Damanhour University focused on AI, machine learning, Python and data science. I've built practical projects across computer vision, document processing, RAG and data analysis.</p><p>My training includes machine learning with NTI, data science and ML with the Central Bank of Egypt, and the ongoing Machine/Data Science track at DEPI. I also work in IT customer service, which keeps my communication and troubleshooting skills sharp.</p></div></div></Sec>

<Sec id="skills" alt><H id="skills" t="Skills & Tech Stack" s="Listed from my CV, no proficiency scores."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(skills).map(([k,v])=><div key={k} className="card rounded-xl border border-line bg-panel p-5"><h3 className="font-medium text-white">{k}</h3><div className="mt-3 flex flex-wrap gap-2">{v.map(c=><Chip key={c} c={c}/>)}</div></div>)}</div></Sec>

<Sec id="services"><H id="services" t="Freelance Services" s="Offerings aligned with my skills and project experience."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=><div key={s.t} className="card rounded-xl border border-line bg-panel p-5 hover:border-blue/60 transition"><h3 className="font-medium text-white">{s.t}</h3><p className="mt-2 text-sm text-slate-400">{s.d}</p><div className="mt-3 flex flex-wrap gap-2">{s.s.map(c=><Chip key={c} c={c}/>)}</div></div>)}</div></Sec>

<Sec id="projects" alt><H id="projects" t="Featured Projects" s="Status is labeled honestly. Open a case study for details."/>
<div role="group" aria-label="Filter projects" className="mb-6 flex flex-wrap gap-2">{filters.map(x=><button key={x} aria-pressed={f===x} onClick={()=>setF(x)} className={'min-h-11 rounded-full border px-4 text-sm '+(f===x?'border-blue bg-blue text-white':'border-line text-slate-300 hover:bg-line')}>{x}</button>)}</div>
<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map(p=><article key={p.id} className="flex flex-col card rounded-xl border border-line bg-panel p-5">
<div className="mb-4 overflow-hidden rounded-lg border border-line bg-ink"><Art id={p.id}/><p className="px-2 pb-1 text-[10px] text-slate-500">Illustrative graphic</p></div>
<h3 className="text-lg font-semibold text-white">{p.title}</h3><p className="text-sm text-slate-400">{p.sub}</p><p className={'mt-2 text-xs '+(p.status.startsWith('Implemented')?'text-emerald-300':p.status.startsWith('Concept')?'text-amber-300':'text-violet-300')}>● {p.status}</p>
<p className="mt-3 text-sm text-slate-300 flex-1">{p.overview}</p><div className="mt-3 flex flex-wrap gap-1.5">{p.stack.slice(0,4).map(c=><Chip key={c} c={c}/>)}</div>
<button onClick={()=>setSel(p)} className={btn+' mt-4 border border-line text-white hover:bg-line'}>View case study</button></article>)}</div>
<div className="mt-8 rounded-xl border border-dashed border-line p-5"><h3 className="font-medium text-white">Concepts & Explorations</h3><p className="mt-1 text-sm text-slate-400">WTHPD? / What Happened? is a planned AI event-understanding concept (computer vision, visual memory, natural-language search). It is not implemented, and not listed as a completed project.</p></div></Sec>

<Sec id="education"><H id="education" t="Education & Certifications" s="Certificate images can be added later in public/certificates."/><div className="grid gap-4 sm:grid-cols-2">{education.map(e=><div key={e.t} className="card rounded-xl border border-line bg-panel p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-medium text-white">{e.t}</h3><span className={'shrink-0 rounded-full px-2.5 py-0.5 text-xs '+(e.n==='Ongoing'?'bg-violet/25 text-violet-200':'bg-blue/20 text-blue-200')}>{e.n}</span></div><p className="mt-1 text-sm text-slate-400">{e.w}</p><p className="mt-2 text-sm text-slate-300">{e.d}</p>{e.cert&&<button onClick={()=>setCert(e.cert!)} className="mt-3 min-h-11 text-sm text-blue hover:underline">View certificate</button>}</div>)}</div>
<p className="mt-6 text-sm text-slate-400">Additional achievements can be added here once documented. Testimonials: coming soon.</p></Sec>

<Sec id="experience" alt><H id="experience" t="Professional Experience"/><div className="max-w-3xl card rounded-xl border border-line bg-panel p-5"><h3 className="font-medium text-white">IT Customer Service · Barcode Agency</h3><p className="text-sm text-slate-400">Jul 2026 – Present · Egypt</p><ul className="mt-3 list-disc space-y-1 pl-5 text-slate-300"><li>Technical customer support for computer and IT issues</li><li>Professional customer communication</li><li>Troubleshooting and problem-solving</li></ul></div></Sec>

<Sec id="contact"><H id="contact" t="Let's Work Together" s="Have a data or AI problem? Get in touch."/><div className="grid gap-8 lg:grid-cols-2">
<div className="space-y-3"><a className={btn+' w-full justify-start border border-line hover:bg-line'} href={'mailto:'+profile.email}><Mail className="h-4 w-4"/>{profile.email}</a><a className={btn+' w-full justify-start border border-line hover:bg-line'} href={'tel:'+profile.phoneTel}><Phone className="h-4 w-4"/>{profile.phone}</a><a className={btn+' w-full justify-start border border-line hover:bg-line'} href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin className="h-4 w-4"/>LinkedIn</a><p className="text-sm text-slate-400">{profile.location}</p></div>
<form onSubmit={submit} noValidate className="space-y-4">{(['name','email','subject'] as const).map(n=><div key={n}><label htmlFor={n} className="mb-1 block text-sm capitalize">{n}</label><input id={n} name={n} type={n==='email'?'email':'text'} className={inp} aria-invalid={!!err[n]}/>{err[n]&&<p role="alert" className="mt-1 text-sm text-red-400">{err[n]}</p>}</div>)}
<div><label htmlFor="message" className="mb-1 block text-sm">Message</label><textarea id="message" name="message" rows={5} className={inp} aria-invalid={!!err.message}/>{err.message&&<p role="alert" className="mt-1 text-sm text-red-400">{err.message}</p>}</div>
<button className={btn+' bg-blue text-white hover:bg-blue/80'}>Open in email app</button><p className="text-xs text-slate-500">No server is connected: this opens your email app with the message prefilled.</p></form></div></Sec>
</main>
<footer className="border-t border-line py-8 text-center text-sm text-slate-500">© {new Date().getFullYear()} {profile.name}</footer>
{top&&<button aria-label="Back to top" onClick={()=>scrollTo({top:0})} className="fixed bottom-5 right-5 h-11 w-11 grid place-items-center rounded-full bg-blue text-white"><ArrowUp className="h-5 w-5"/></button>}
{cert&&<Lightbox src={cert} onClose={()=>setCert(null)}/>}{sel&&<Modal p={sel} onClose={()=>setSel(null)}/>}</>)}
